### PR TITLE
A bunch of controller, keyboard and mouse improvements, plus a few extra fixes

### PR DESCRIPTION
**Pull request by AdrianoML**
Gamepads now have proper analog movement, better keybindings and proper menu support (still missing an OSK tough...). They also don't share bindings with keyboard anymore.
Support for a full keyboard with a modern default keybinding applyed when a game first boots

Things I haven't looked into:
I'm not sure how I let the user switch from digital to analog or inverted control sticks. 
I hardcoded a deadzone and a range value for the sticks. Is there a way to acquire then from retroarch?

### CODE REVIEW

**Comment by twinaphex** [comment]
It's not possible to get the deadzone values from the frontend. However, we could add an environment callback to the libretro API so that you could effectively do the same. It would be up to the frontend to implement it then, so in case a frontend doesn't implement it, you should still provide a default fallback (could be the current situation we have now).

**Comment by twinaphex** [comment]
Question though - I play Tyrquake mainly with the gamepad. The new default gamepad controls might be suitable to you but I can't really play like that. Could you add in a menu setting so we can toggle between the current gamepad layout and the old one?

Also, there is another thing which would be great if we could backport it from another source port - scaled menu graphics so that it's not too small at high resolutions.

**Comment by AdrianoML** [comment]
Do you want just the old keybindings or also the old analog joystick behaviour? (which had digital input)

**Comment by twinaphex** [comment]
Analog stick input seems fine, it's just the digital buttons that I'd like on a separate gamepad layout.

**Comment by AdrianoML** [comment]
I'm not used to playing FPS's with gamepads, so i wasn't sure how popular the diamond buttons are for main actions (like shooting or jumping), and I thought it was unusual to have look up and down at L2 and R2 for example. Anyway, will look into it.

**Comment by twinaphex** [comment]
Thanks.

**Pull request merged**
